name: firewall-build
on: [push]


jobs:

  native-build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      
      - name: Fetch submodule firewall
        run: |
          git config -f .gitmodules submodule.firewall.url https://github.com/smart-home-network-security/firewall-blocklist.git
          git submodule sync firewall
          git submodule update --init --recursive firewall
      
      - name: Install packages
        run: sudo .ci_scripts/firewall-test/install_packages.sh
      
      - name: Build project
        run: ./build.sh -T
      
      - name: Run unit tests
        run: .ci_scripts/firewall-test/run_tests.sh

      - name: Run unit tests with Valgrind
        run: .ci_scripts/firewall-test/run_tests.sh valgrind
      
      - name: Run Cppcheck
        run: .ci_scripts/firewall-test/run_cppcheck.sh
      
      - name: Add nftables rules
        run: .ci_scripts/firewall-test/add_nft_rules.sh
  
  
  cross-compilation:
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Fetch submodule firewall
        run: |
          git config -f .gitmodules submodule.firewall.url https://github.com/smart-home-network-security/firewall-blocklist.git
          git submodule sync firewall
          git submodule update --init --recursive firewall

      - name: Run cross-compilation
        run: docker compose run --rm --remove-orphans cross-compilation /home/user/iot-firewall/docker_cmd.sh tl-wdr4900 $(id -u $(whoami)) $(id -g $(whoami))
