name: python-unit-tests
on: [push]


jobs:

  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
      
      - name: Sparse checkout
        run: |
          git sparse-checkout init
          echo "/*" >> .git/info/sparse-checkout
          echo "!/data/" >> .git/info/sparse-checkout
          git read-tree -mu HEAD

      - name: Install Python packages
        run: pip3 install -r requirements.txt

      - name: Install test package
        run: pip3 install pytest

      - name: Run tests
        run: pytest $GITHUB_WORKSPACE/test/
